//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coditech.Resources.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete admin role due to associate record..
        /// </summary>
        public static string ErrorDeleteAdminRoleMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteAdminRoleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete admin saction post due to associate record..
        /// </summary>
        public static string ErrorDeleteAdminSanctionPost {
            get {
                return ResourceManager.GetString("ErrorDeleteAdminSanctionPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete city due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralCityMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralCityMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete country due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralCountryMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralCountryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete department due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralDepartmentMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralDepartmentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete designation due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralDesignationMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralDesignationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete nationality due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralNationalityMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralNationalityMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete tax group due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralTaxGroupMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralTaxGroupMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete tax due to associate record..
        /// </summary>
        public static string ErrorDeleteGeneralTaxMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteGeneralTaxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete organisationCentre due to associate record..
        /// </summary>
        public static string ErrorDeleteOrganisationCentreMaster {
            get {
                return ResourceManager.GetString("ErrorDeleteOrganisationCentreMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not exist. Enter a valid email address or password.
        /// </summary>
        public static string ErrorMessage_ThisaccountdoesnotexistEnteravalidemailaddressorpassword {
            get {
                return ResourceManager.GetString("ErrorMessage_ThisaccountdoesnotexistEnteravalidemailaddressorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Role List.
        /// </summary>
        public static string LabelAdminRoleList {
            get {
                return ResourceManager.GetString("LabelAdminRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Sanction Post List.
        /// </summary>
        public static string LabelAdminSanctionPostList {
            get {
                return ResourceManager.GetString("LabelAdminSanctionPostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string LabelCentre {
            get {
                return ResourceManager.GetString("LabelCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City List.
        /// </summary>
        public static string LabelCityList {
            get {
                return ResourceManager.GetString("LabelCityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country List.
        /// </summary>
        public static string LabelCountryList {
            get {
                return ResourceManager.GetString("LabelCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        public static string LabelDepartmentList {
            get {
                return ResourceManager.GetString("LabelDepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string LabelDepartments {
            get {
                return ResourceManager.GetString("LabelDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation List.
        /// </summary>
        public static string LabelDesignationList {
            get {
                return ResourceManager.GetString("LabelDesignationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string LabelIsActive {
            get {
                return ResourceManager.GetString("LabelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalityList.
        /// </summary>
        public static string LabelNationalityList {
            get {
                return ResourceManager.GetString("LabelNationalityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation List.
        /// </summary>
        public static string LabelOrganisationList {
            get {
                return ResourceManager.GetString("LabelOrganisationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group List.
        /// </summary>
        public static string LabelTaxGroupList {
            get {
                return ResourceManager.GetString("LabelTaxGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax List.
        /// </summary>
        public static string LabelTaxList {
            get {
                return ResourceManager.GetString("LabelTaxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Select Centre-----.
        /// </summary>
        public static string SelectCentre {
            get {
                return ResourceManager.GetString("SelectCentre", resourceCulture);
            }
        }
    }
}
