//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coditech.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Change Password Success Message updated successfully..
        /// </summary>
        public static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the record..
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted Inventory Category successfully..
        /// </summary>
        public static string DeleteInventoryCategory {
            get {
                return ResourceManager.GetString("DeleteInventoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted Inventory Item Storage Dimension successfully..
        /// </summary>
        public static string DeleteInventoryItemStorageDimension {
            get {
                return ResourceManager.GetString("DeleteInventoryItemStorageDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string ErrorCodeExists {
            get {
                return ResourceManager.GetString("ErrorCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create.
        /// </summary>
        public static string ErrorFailedToCreate {
            get {
                return ResourceManager.GetString("ErrorFailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the selected record..
        /// </summary>
        public static string ErrorFailedToDelete {
            get {
                return ResourceManager.GetString("ErrorFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size limit exceed. It should be below{0} MB..
        /// </summary>
        public static string ErrorFileSizeLimitExceed {
            get {
                return ResourceManager.GetString("ErrorFileSizeLimitExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be less than 1..
        /// </summary>
        public static string ErrorIdLessThanOne {
            get {
                return ResourceManager.GetString("ErrorIdLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Extension.
        /// </summary>
        public static string ErrorInvalidFileExtension {
            get {
                return ResourceManager.GetString("ErrorInvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name..
        /// </summary>
        public static string ErrorInvalidFileName {
            get {
                return ResourceManager.GetString("ErrorInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder path..
        /// </summary>
        public static string ErrorInvalidFolderPath {
            get {
                return ResourceManager.GetString("ErrorInvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Contact Your Administrator.
        /// </summary>
        public static string ErrorMessage_PleaseContactYourAdministrator {
            get {
                return ResourceManager.GetString("ErrorMessage_PleaseContactYourAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string LabelIsActive {
            get {
                return ResourceManager.GetString("LabelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model can not be null..
        /// </summary>
        public static string ModelNotNull {
            get {
                return ResourceManager.GetString("ModelNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record added successfully..
        /// </summary>
        public static string RecordAddedSuccessMessage {
            get {
                return ResourceManager.GetString("RecordAddedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------Select----------.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update record..
        /// </summary>
        public static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated Inventory Category successfully..
        /// </summary>
        public static string UpdateInventoryCategory {
            get {
                return ResourceManager.GetString("UpdateInventoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update record.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
    }
}
