name: Deploy-Stage-Coditech

on: 

  workflow_dispatch:

     inputs:
       coditech_build:
         description: 'Build Coditech'
         required: true
         default: true
         type: boolean
       admin_deploy:
         description: 'Deloy Admin'
         required: true
         default: false
         type: boolean
       employee_api_deploy:
         description: 'Deloy Employee API'
         required: true
         default: false
         type: boolean
       gymmanagementsystem_api_deploy:
         description: 'Deloy GymManagementSystem API'
         required: true
         default: false
         type: boolean
       inventory_api_deploy:
         description: 'Deloy Inventory API'
         required: true
         default: false
         type: boolean
       mediamanager_api_deploy:
         description: 'Deloy MediaManager API'
         required: true
         default: false
         type: boolean
       organisation_api_deploy:
         description: 'Deloy Organisation API'
         required: true
         default: false
         type: boolean

jobs:
  coditech_build:
    runs-on: [self-hosted, Windows, x64, coditech_Stage]
    if: github.event.inputs.coditech_build == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # with:
          # ref: Stage

      - name: Restore Packages
        run: | 
           & "C:\\GitAction\\nugettools\\nuget.exe" restore './Coditech.Project/Coditech.Project.sln' -DirectDownload -MSBuildPath "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\"

      - name: Build
        run: | 
           & "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\msbuild.exe"  './Coditech.Project/Coditech.Project.sln' /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="./publish/Release" /p:Configuration=Release /p:TransformConfigFiles=false

  # admin_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.admin_deploy == 'true'
    
  #   steps:
  #     - name: Stop ADMIN IIS Site and App Pool
  #       run: |
  #         # Stop the IIS site
  #         Stop-WebSite -Name "pahpc-admin" 

  #         # Stop the associated app pool
  #         Stop-WebAppPool -Name "pahpc-admin"

  #         # Wait for a few seconds (optional, if needed)
  #         Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\Admin\Coditech.Admin\bin\Release\net8.0\*  -Destination C:\HostingSites\CoditechStage\Admin\ -Recurse -Force

  #     - name: Start ADMIN IIS Site and App Pool
  #       run: |
  #         # Start the IIS site
  #         Start-WebSite -Name "pahpc-admin"

  #         # Start the associated app pool
  #         Start-WebAppPool -Name "pahpc-admin"

  # employee_api_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.employee_api_deploy == 'true'

  #   steps:
  #     - name: Stop Employee API IIS Site and App Pool
  #       run: |
  #         # Stop the IIS site
  #         Stop-WebSite -Name "pahpc-api-employee" 

  #         # Stop the associated app pool
  #         Stop-WebAppPool -Name "pahpc-api-employee"

  #         # Wait for a few seconds (optional, if needed)
  #         Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\API\Coditech.Engine.Employee\bin\Release\net8.0\* -Destination C:\HostingSites\CoditechStage\Employee\ -Recurse -Force 

  #     - name: Start Employee API IIS Site and App Pool
  #       run: |
  #         # Start the IIS site
  #         Start-WebSite -Name "pahpc-api-employee"

  #         # Start the associated app pool
  #         Start-WebAppPool -Name "pahpc-api-employee"

  # gymmanagementsystem_api_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.gymmanagementsystem_api_deploy == 'true'

  #   steps:
  #     - name: Stop GymManagementSystem IIS Site and App Pool
  #       run: |
  #         # Stop the IIS site
  #         Stop-WebSite -Name "pahpc-api-gymmanagementsystem" 

  #         # Stop the associated app pool
  #         Stop-WebAppPool -Name "pahpc-api-gymmanagementsystem"

  #         # Wait for a few seconds (optional, if needed)
  #         Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\API\Coditech.Engine.GymManagementSystem\bin\Release\net8.0\*  -Destination C:\HostingSites\CoditechStage\GMS\ -Recurse -Force 

  #     - name: Start GymManagementSystem IIS Site and App Pool
  #       run: |
  #         # Start the IIS site
  #         Start-WebSite -Name "pahpc-api-gymmanagementsystem"

  #         # Start the associated app pool
  #         Start-WebAppPool -Name "pahpc-api-gymmanagementsystem"

  # inventory_api_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.inventory_api_deploy == 'true'

  #   steps:

  #     - name: Stop Inventory IIS Site and App Pool
  #       run: |
  #          # Stop the IIS site
  #          Stop-WebSite -Name "pahpc-api-inventory" 
  #          # Stop the associated app pool
  #          Stop-WebAppPool -Name "pahpc-api-inventory"

  #          # Wait for a few seconds (optional, if needed)
  #          Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\API\Coditech.Engine.Inventory\bin\Release\net8.0\* -Destination C:\HostingSites\CoditechStage\Inventory\ -Recurse -Force 

  #     - name: Start Payment IIS Site and App Pool
  #       run: |
  #          # Start the IIS site
  #          Start-WebSite -Name "pahpc-api-inventory"
  #          # Start the associated app pool
  #          Start-WebAppPool -Name "pahpc-api-inventory"

  # mediamanager_api_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.mediamanager_api_deploy == 'true'

  #   steps:

  #     - name: Stop MediaManager IIS Site and App Pool
  #       run: |
  #          # Stop the IIS site
  #          Stop-WebSite -Name "pahpc-api-mediamanager" 
  #          # Stop the associated app pool
  #          Stop-WebAppPool -Name "pahpc-api-mediamanager"

  #          # Wait for a few seconds (optional, if needed)
  #          Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\API\Coditech.Engine.MediaManager\bin\Release\net8.0\* -Destination C:\HostingSites\CoditechStage\MediaManager\ -Recurse -Force 

  #     - name: Start MediaManager IIS Site and App Pool
  #       run: |
  #          # Start the IIS site
  #          Start-WebSite -Name "pahpc-api-mediamanager"
  #          # Start the associated app pool
  #          Start-WebAppPool -Name "pahpc-api-mediamanager"

  # organisation_api_deploy:
  #   runs-on: [self-hosted, Windows, x64, coditech_Stage]
  #   needs: coditech_build
  #   if: github.event.inputs.organisation_api_deploy == 'true'

  #   steps:
  #     - name: Stop Organisation IIS Site and App Pool
  #       run: |
  #          # Stop the IIS site
  #          Stop-WebSite -Name "pahpc-api-organisation" 
  #          # Stop the associated app pool
  #          Stop-WebAppPool -Name "pahpc-api-organisation"

  #          # Wait for a few seconds (optional, if needed)
  #          Start-Sleep -Seconds 5

  #     - name: Copy Build file
  #       run: Copy-Item -Path C:\GitAction\CoditechStage\_work\CoditechStage\CoditechStage\Coditech.Project\API\Coditech.Engine.Organisation\bin\Release\net8.0\* -Destination C:\HostingSites\CoditechStage\Organisation\ -Recurse -Force 

  #     - name: Start Organisation IIS Site and App Pool
  #       run: |
  #          # Start the IIS site
  #          Start-WebSite -Name "pahpc-api-organisation"
  #          # Start the associated app pool
  #          Start-WebAppPool -Name "pahpc-api-organisation"